"""add_crm_tables

Revision ID: 08d9b0500c67
Revises: 2dcf3536802a
Create Date: 2026-06-25 17:10:28.230608

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d9b0500c67'
down_revision: Union[str, None] = '2dcf3536802a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_pipelines',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_pipelines_id'), 'crm_pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_crm_pipelines_is_deleted'), 'crm_pipelines', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_pipelines_organization_id'), 'crm_pipelines', ['organization_id'], unique=False)
    op.create_table('crm_tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_tags_id'), 'crm_tags', ['id'], unique=False)
    op.create_index(op.f('ix_crm_tags_is_deleted'), 'crm_tags', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_tags_organization_id'), 'crm_tags', ['organization_id'], unique=False)
    op.create_table('crm_activities',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('note', 'call', 'email', 'meeting', 'task', 'whatsapp', name='activitytype'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_activities_entity_id'), 'crm_activities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_id'), 'crm_activities', ['id'], unique=False)
    op.create_index(op.f('ix_crm_activities_is_deleted'), 'crm_activities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_activities_organization_id'), 'crm_activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_owner_id'), 'crm_activities', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_public_id'), 'crm_activities', ['public_id'], unique=True)
    op.create_table('crm_companies',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('size', sa.Enum('startup', 'small', 'medium', 'enterprise', name='companysize'), nullable=True),
    sa.Column('status', sa.Enum('prospect', 'customer', 'churned', 'partner', name='companystatus'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_companies_id'), 'crm_companies', ['id'], unique=False)
    op.create_index(op.f('ix_crm_companies_is_deleted'), 'crm_companies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_companies_name'), 'crm_companies', ['name'], unique=False)
    op.create_index(op.f('ix_crm_companies_organization_id'), 'crm_companies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_companies_owner_id'), 'crm_companies', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_companies_public_id'), 'crm_companies', ['public_id'], unique=True)
    op.create_table('crm_pipeline_stages',
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_won_stage', sa.Boolean(), nullable=False),
    sa.Column('is_lost_stage', sa.Boolean(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_pipeline_stages_id'), 'crm_pipeline_stages', ['id'], unique=False)
    op.create_index(op.f('ix_crm_pipeline_stages_is_deleted'), 'crm_pipeline_stages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_pipeline_stages_pipeline_id'), 'crm_pipeline_stages', ['pipeline_id'], unique=False)
    op.create_table('crm_contacts',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_contacts_company_id'), 'crm_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_id'), 'crm_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_is_deleted'), 'crm_contacts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_contacts_organization_id'), 'crm_contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_owner_id'), 'crm_contacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_public_id'), 'crm_contacts', ['public_id'], unique=True)
    op.create_table('crm_leads',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('website', 'referral', 'cold_call', 'linkedin', 'ad', 'event', 'other', name='leadsource'), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'unqualified', 'converted', name='leadstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='leadpriority'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], name='fk_crm_leads_deal_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_company_id'), 'crm_leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_contact_id'), 'crm_leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_deal_id'), 'crm_leads', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_id'), 'crm_leads', ['id'], unique=False)
    op.create_index(op.f('ix_crm_leads_is_deleted'), 'crm_leads', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_leads_organization_id'), 'crm_leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_owner_id'), 'crm_leads', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_public_id'), 'crm_leads', ['public_id'], unique=True)
    op.create_table('crm_deals',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'won', 'lost', 'on_hold', name='dealstatus'), nullable=False),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipelines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['crm_pipeline_stages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_deals_company_id'), 'crm_deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_contact_id'), 'crm_deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_id'), 'crm_deals', ['id'], unique=False)
    op.create_index(op.f('ix_crm_deals_is_deleted'), 'crm_deals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_deals_lead_id'), 'crm_deals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_organization_id'), 'crm_deals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_owner_id'), 'crm_deals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_pipeline_id'), 'crm_deals', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_public_id'), 'crm_deals', ['public_id'], unique=True)
    op.create_index(op.f('ix_crm_deals_stage_id'), 'crm_deals', ['stage_id'], unique=False)
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'trial'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_crm_deals_stage_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_public_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_pipeline_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_owner_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_organization_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_lead_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_is_deleted'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_contact_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_company_id'), table_name='crm_deals')
    op.drop_table('crm_deals')
    op.drop_index(op.f('ix_crm_leads_public_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_owner_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_organization_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_is_deleted'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_deal_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_contact_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_company_id'), table_name='crm_leads')
    op.drop_table('crm_leads')
    op.drop_index(op.f('ix_crm_contacts_public_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_owner_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_organization_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_is_deleted'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_company_id'), table_name='crm_contacts')
    op.drop_table('crm_contacts')
    op.drop_index(op.f('ix_crm_pipeline_stages_pipeline_id'), table_name='crm_pipeline_stages')
    op.drop_index(op.f('ix_crm_pipeline_stages_is_deleted'), table_name='crm_pipeline_stages')
    op.drop_index(op.f('ix_crm_pipeline_stages_id'), table_name='crm_pipeline_stages')
    op.drop_table('crm_pipeline_stages')
    op.drop_index(op.f('ix_crm_companies_public_id'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_owner_id'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_organization_id'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_name'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_is_deleted'), table_name='crm_companies')
    op.drop_index(op.f('ix_crm_companies_id'), table_name='crm_companies')
    op.drop_table('crm_companies')
    op.drop_index(op.f('ix_crm_activities_public_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_owner_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_organization_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_is_deleted'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_entity_id'), table_name='crm_activities')
    op.drop_table('crm_activities')
    op.drop_index(op.f('ix_crm_tags_organization_id'), table_name='crm_tags')
    op.drop_index(op.f('ix_crm_tags_is_deleted'), table_name='crm_tags')
    op.drop_index(op.f('ix_crm_tags_id'), table_name='crm_tags')
    op.drop_table('crm_tags')
    op.drop_index(op.f('ix_crm_pipelines_organization_id'), table_name='crm_pipelines')
    op.drop_index(op.f('ix_crm_pipelines_is_deleted'), table_name='crm_pipelines')
    op.drop_index(op.f('ix_crm_pipelines_id'), table_name='crm_pipelines')
    op.drop_table('crm_pipelines')
    # ### end Alembic commands ###
