"""add_pricing_plans

Revision ID: 03640c1f2a93
Revises: b40161f08d59
Create Date: 2026-06-20 14:58:34.156586

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03640c1f2a93'
down_revision: Union[str, None] = 'b40161f08d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('tier', sa.Enum('basic', 'pro', 'enterprise', name='plantier'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled_modules', sa.JSON(), nullable=False),
    sa.Column('ai_monthly_limit', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_is_deleted'), 'plans', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plans_tier'), 'plans', ['tier'], unique=True)
    op.create_table('ai_usage_counters',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'period_start', name='uq_ai_usage_org_period')
    )
    op.create_index(op.f('ix_ai_usage_counters_id'), 'ai_usage_counters', ['id'], unique=False)
    op.create_index(op.f('ix_ai_usage_counters_is_deleted'), 'ai_usage_counters', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_usage_counters_organization_id'), 'ai_usage_counters', ['organization_id'], unique=False)
    op.add_column('organizations', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_organizations_plan_id'), 'organizations', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'organizations', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_index(op.f('ix_organizations_plan_id'), table_name='organizations')
    op.drop_column('organizations', 'plan_id')
    op.drop_index(op.f('ix_ai_usage_counters_organization_id'), table_name='ai_usage_counters')
    op.drop_index(op.f('ix_ai_usage_counters_is_deleted'), table_name='ai_usage_counters')
    op.drop_index(op.f('ix_ai_usage_counters_id'), table_name='ai_usage_counters')
    op.drop_table('ai_usage_counters')
    op.drop_index(op.f('ix_plans_tier'), table_name='plans')
    op.drop_index(op.f('ix_plans_is_deleted'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
