"""add_hr_checklist_and_document_tables

Revision ID: 97986451f5d4
Revises: b4e4a0978adc
Create Date: 2026-07-11 18:02:11.243160

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97986451f5d4'
down_revision: Union[str, None] = 'b4e4a0978adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_checklist_templates',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('checklist_type', sa.Enum('onboarding', 'offboarding', name='checklisttype'), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_checklist_templates_checklist_type'), 'hr_checklist_templates', ['checklist_type'], unique=False)
    op.create_index(op.f('ix_hr_checklist_templates_id'), 'hr_checklist_templates', ['id'], unique=False)
    op.create_index(op.f('ix_hr_checklist_templates_is_deleted'), 'hr_checklist_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_checklist_templates_organization_id'), 'hr_checklist_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hr_checklist_templates_public_id'), 'hr_checklist_templates', ['public_id'], unique=True)
    op.create_table('hr_checklist_instances',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', name='checkliststatus'), nullable=False),
    sa.Column('task_statuses', sa.JSON(), nullable=False),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['hr_checklist_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_checklist_instances_id'), 'hr_checklist_instances', ['id'], unique=False)
    op.create_index(op.f('ix_hr_checklist_instances_is_deleted'), 'hr_checklist_instances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_checklist_instances_organization_id'), 'hr_checklist_instances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hr_checklist_instances_public_id'), 'hr_checklist_instances', ['public_id'], unique=True)
    op.create_index(op.f('ix_hr_checklist_instances_status'), 'hr_checklist_instances', ['status'], unique=False)
    op.create_index(op.f('ix_hr_checklist_instances_template_id'), 'hr_checklist_instances', ['template_id'], unique=False)
    op.create_index(op.f('ix_hr_checklist_instances_user_id'), 'hr_checklist_instances', ['user_id'], unique=False)
    op.create_table('hr_employee_documents',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_employee_documents_id'), 'hr_employee_documents', ['id'], unique=False)
    op.create_index(op.f('ix_hr_employee_documents_is_deleted'), 'hr_employee_documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_employee_documents_organization_id'), 'hr_employee_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hr_employee_documents_public_id'), 'hr_employee_documents', ['public_id'], unique=True)
    op.create_index(op.f('ix_hr_employee_documents_user_id'), 'hr_employee_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_employee_documents_user_id'), table_name='hr_employee_documents')
    op.drop_index(op.f('ix_hr_employee_documents_public_id'), table_name='hr_employee_documents')
    op.drop_index(op.f('ix_hr_employee_documents_organization_id'), table_name='hr_employee_documents')
    op.drop_index(op.f('ix_hr_employee_documents_is_deleted'), table_name='hr_employee_documents')
    op.drop_index(op.f('ix_hr_employee_documents_id'), table_name='hr_employee_documents')
    op.drop_table('hr_employee_documents')
    op.drop_index(op.f('ix_hr_checklist_instances_user_id'), table_name='hr_checklist_instances')
    op.drop_index(op.f('ix_hr_checklist_instances_template_id'), table_name='hr_checklist_instances')
    op.drop_index(op.f('ix_hr_checklist_instances_status'), table_name='hr_checklist_instances')
    op.drop_index(op.f('ix_hr_checklist_instances_public_id'), table_name='hr_checklist_instances')
    op.drop_index(op.f('ix_hr_checklist_instances_organization_id'), table_name='hr_checklist_instances')
    op.drop_index(op.f('ix_hr_checklist_instances_is_deleted'), table_name='hr_checklist_instances')
    op.drop_index(op.f('ix_hr_checklist_instances_id'), table_name='hr_checklist_instances')
    op.drop_table('hr_checklist_instances')
    op.drop_index(op.f('ix_hr_checklist_templates_public_id'), table_name='hr_checklist_templates')
    op.drop_index(op.f('ix_hr_checklist_templates_organization_id'), table_name='hr_checklist_templates')
    op.drop_index(op.f('ix_hr_checklist_templates_is_deleted'), table_name='hr_checklist_templates')
    op.drop_index(op.f('ix_hr_checklist_templates_id'), table_name='hr_checklist_templates')
    op.drop_index(op.f('ix_hr_checklist_templates_checklist_type'), table_name='hr_checklist_templates')
    op.drop_table('hr_checklist_templates')
    # ### end Alembic commands ###
