"""add_free_tier_and_user_limit

Revision ID: 2dcf3536802a
Revises: 0b9c168fe303
Create Date: 2026-06-21 11:05:23.630817

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dcf3536802a'
down_revision: Union[str, None] = '0b9c168fe303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Commit the transaction so ALTER TYPE ADD VALUE can execute without active txn (PostgreSQL constraint)
    op.execute("COMMIT")
    op.execute("ALTER TYPE plantier ADD VALUE 'free'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('user_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'user_limit')
    # ### end Alembic commands ###
