"""add_hr_payroll_tables

Revision ID: b4e4a0978adc
Revises: 1ff850054cd0
Create Date: 2026-07-11 17:46:44.927278

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4e4a0978adc'
down_revision: Union[str, None] = '1ff850054cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_salary_components',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('component_type', sa.Enum('earning', 'deduction', name='salarycomponenttype'), nullable=False),
    sa.Column('is_statutory', sa.Boolean(), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_salary_components_code'), 'hr_salary_components', ['code'], unique=False)
    op.create_index(op.f('ix_hr_salary_components_id'), 'hr_salary_components', ['id'], unique=False)
    op.create_index(op.f('ix_hr_salary_components_is_deleted'), 'hr_salary_components', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_salary_components_organization_id'), 'hr_salary_components', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hr_salary_components_public_id'), 'hr_salary_components', ['public_id'], unique=True)
    op.create_table('hr_salary_structures',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_salary_structures_id'), 'hr_salary_structures', ['id'], unique=False)
    op.create_index(op.f('ix_hr_salary_structures_is_deleted'), 'hr_salary_structures', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_salary_structures_organization_id'), 'hr_salary_structures', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hr_salary_structures_public_id'), 'hr_salary_structures', ['public_id'], unique=True)
    op.create_table('hr_employee_salaries',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('ctc', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['hr_salary_structures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_employee_salaries_id'), 'hr_employee_salaries', ['id'], unique=False)
    op.create_index(op.f('ix_hr_employee_salaries_is_deleted'), 'hr_employee_salaries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_employee_salaries_organization_id'), 'hr_employee_salaries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hr_employee_salaries_public_id'), 'hr_employee_salaries', ['public_id'], unique=True)
    op.create_index(op.f('ix_hr_employee_salaries_structure_id'), 'hr_employee_salaries', ['structure_id'], unique=False)
    op.create_index(op.f('ix_hr_employee_salaries_user_id'), 'hr_employee_salaries', ['user_id'], unique=True)
    op.create_table('hr_payroll_runs',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'processing', 'finalized', name='payrollrunstatus'), nullable=False),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_payroll_runs_id'), 'hr_payroll_runs', ['id'], unique=False)
    op.create_index(op.f('ix_hr_payroll_runs_is_deleted'), 'hr_payroll_runs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_payroll_runs_month'), 'hr_payroll_runs', ['month'], unique=False)
    op.create_index(op.f('ix_hr_payroll_runs_organization_id'), 'hr_payroll_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hr_payroll_runs_public_id'), 'hr_payroll_runs', ['public_id'], unique=True)
    op.create_index(op.f('ix_hr_payroll_runs_status'), 'hr_payroll_runs', ['status'], unique=False)
    op.create_index(op.f('ix_hr_payroll_runs_year'), 'hr_payroll_runs', ['year'], unique=False)
    op.create_table('hr_salary_structure_items',
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('salary_component_id', sa.Integer(), nullable=False),
    sa.Column('calculation_type', sa.Enum('flat', 'formula', name='salarycalculationtype'), nullable=False),
    sa.Column('value_expr', sa.String(length=255), nullable=False),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['salary_component_id'], ['hr_salary_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['hr_salary_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_salary_structure_items_id'), 'hr_salary_structure_items', ['id'], unique=False)
    op.create_index(op.f('ix_hr_salary_structure_items_is_deleted'), 'hr_salary_structure_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_salary_structure_items_salary_component_id'), 'hr_salary_structure_items', ['salary_component_id'], unique=False)
    op.create_index(op.f('ix_hr_salary_structure_items_structure_id'), 'hr_salary_structure_items', ['structure_id'], unique=False)
    op.create_table('hr_payslips',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('earnings_breakdown', sa.JSON(), nullable=False),
    sa.Column('deductions_breakdown', sa.JSON(), nullable=False),
    sa.Column('gross_earnings', sa.Float(), nullable=False),
    sa.Column('total_deductions', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('lop_days', sa.Float(), nullable=False),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['hr_payroll_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_payslips_id'), 'hr_payslips', ['id'], unique=False)
    op.create_index(op.f('ix_hr_payslips_is_deleted'), 'hr_payslips', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_payslips_organization_id'), 'hr_payslips', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hr_payslips_payroll_run_id'), 'hr_payslips', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_hr_payslips_public_id'), 'hr_payslips', ['public_id'], unique=True)
    op.create_index(op.f('ix_hr_payslips_user_id'), 'hr_payslips', ['user_id'], unique=False)
    op.create_table('hr_variable_pay_entries',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_type', sa.Enum('earning', 'deduction', name='salarycomponenttype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['hr_payroll_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_variable_pay_entries_id'), 'hr_variable_pay_entries', ['id'], unique=False)
    op.create_index(op.f('ix_hr_variable_pay_entries_is_deleted'), 'hr_variable_pay_entries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_variable_pay_entries_organization_id'), 'hr_variable_pay_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hr_variable_pay_entries_payroll_run_id'), 'hr_variable_pay_entries', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_hr_variable_pay_entries_public_id'), 'hr_variable_pay_entries', ['public_id'], unique=True)
    op.create_index(op.f('ix_hr_variable_pay_entries_user_id'), 'hr_variable_pay_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_variable_pay_entries_user_id'), table_name='hr_variable_pay_entries')
    op.drop_index(op.f('ix_hr_variable_pay_entries_public_id'), table_name='hr_variable_pay_entries')
    op.drop_index(op.f('ix_hr_variable_pay_entries_payroll_run_id'), table_name='hr_variable_pay_entries')
    op.drop_index(op.f('ix_hr_variable_pay_entries_organization_id'), table_name='hr_variable_pay_entries')
    op.drop_index(op.f('ix_hr_variable_pay_entries_is_deleted'), table_name='hr_variable_pay_entries')
    op.drop_index(op.f('ix_hr_variable_pay_entries_id'), table_name='hr_variable_pay_entries')
    op.drop_table('hr_variable_pay_entries')
    op.drop_index(op.f('ix_hr_payslips_user_id'), table_name='hr_payslips')
    op.drop_index(op.f('ix_hr_payslips_public_id'), table_name='hr_payslips')
    op.drop_index(op.f('ix_hr_payslips_payroll_run_id'), table_name='hr_payslips')
    op.drop_index(op.f('ix_hr_payslips_organization_id'), table_name='hr_payslips')
    op.drop_index(op.f('ix_hr_payslips_is_deleted'), table_name='hr_payslips')
    op.drop_index(op.f('ix_hr_payslips_id'), table_name='hr_payslips')
    op.drop_table('hr_payslips')
    op.drop_index(op.f('ix_hr_salary_structure_items_structure_id'), table_name='hr_salary_structure_items')
    op.drop_index(op.f('ix_hr_salary_structure_items_salary_component_id'), table_name='hr_salary_structure_items')
    op.drop_index(op.f('ix_hr_salary_structure_items_is_deleted'), table_name='hr_salary_structure_items')
    op.drop_index(op.f('ix_hr_salary_structure_items_id'), table_name='hr_salary_structure_items')
    op.drop_table('hr_salary_structure_items')
    op.drop_index(op.f('ix_hr_payroll_runs_year'), table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_status'), table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_public_id'), table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_organization_id'), table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_month'), table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_is_deleted'), table_name='hr_payroll_runs')
    op.drop_index(op.f('ix_hr_payroll_runs_id'), table_name='hr_payroll_runs')
    op.drop_table('hr_payroll_runs')
    op.drop_index(op.f('ix_hr_employee_salaries_user_id'), table_name='hr_employee_salaries')
    op.drop_index(op.f('ix_hr_employee_salaries_structure_id'), table_name='hr_employee_salaries')
    op.drop_index(op.f('ix_hr_employee_salaries_public_id'), table_name='hr_employee_salaries')
    op.drop_index(op.f('ix_hr_employee_salaries_organization_id'), table_name='hr_employee_salaries')
    op.drop_index(op.f('ix_hr_employee_salaries_is_deleted'), table_name='hr_employee_salaries')
    op.drop_index(op.f('ix_hr_employee_salaries_id'), table_name='hr_employee_salaries')
    op.drop_table('hr_employee_salaries')
    op.drop_index(op.f('ix_hr_salary_structures_public_id'), table_name='hr_salary_structures')
    op.drop_index(op.f('ix_hr_salary_structures_organization_id'), table_name='hr_salary_structures')
    op.drop_index(op.f('ix_hr_salary_structures_is_deleted'), table_name='hr_salary_structures')
    op.drop_index(op.f('ix_hr_salary_structures_id'), table_name='hr_salary_structures')
    op.drop_table('hr_salary_structures')
    op.drop_index(op.f('ix_hr_salary_components_public_id'), table_name='hr_salary_components')
    op.drop_index(op.f('ix_hr_salary_components_organization_id'), table_name='hr_salary_components')
    op.drop_index(op.f('ix_hr_salary_components_is_deleted'), table_name='hr_salary_components')
    op.drop_index(op.f('ix_hr_salary_components_id'), table_name='hr_salary_components')
    op.drop_index(op.f('ix_hr_salary_components_code'), table_name='hr_salary_components')
    op.drop_table('hr_salary_components')
    # ### end Alembic commands ###
