"""add_project_phase_and_issues

Revision ID: 6e3c76db9e0e
Revises: c53c44ed3a07
Create Date: 2026-07-04 17:16:11.946394

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e3c76db9e0e'
down_revision: Union[str, None] = 'c53c44ed3a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('phase', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('issues', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'issues')
    op.drop_column('projects', 'phase')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
