"""add_trial_system

Revision ID: b40161f08d59
Revises: 748ea952ff90
Create Date: 2026-06-20 14:27:39.427480

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40161f08d59'
down_revision: Union[str, None] = '748ea952ff90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trial_email_registry',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_email_registry_email'), 'trial_email_registry', ['email'], unique=True)
    op.create_index(op.f('ix_trial_email_registry_id'), 'trial_email_registry', ['id'], unique=False)
    op.create_index(op.f('ix_trial_email_registry_is_deleted'), 'trial_email_registry', ['is_deleted'], unique=False)
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=50), nullable=False, server_default='trial'))
    op.add_column('organizations', sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'trial_expires_at')
    op.drop_column('organizations', 'trial_started_at')
    op.drop_column('organizations', 'subscription_status')
    op.drop_index(op.f('ix_trial_email_registry_is_deleted'), table_name='trial_email_registry')
    op.drop_index(op.f('ix_trial_email_registry_id'), table_name='trial_email_registry')
    op.drop_index(op.f('ix_trial_email_registry_email'), table_name='trial_email_registry')
    op.drop_table('trial_email_registry')
    # ### end Alembic commands ###
