"""create_crm_files

Revision ID: c3196d4def85
Revises: 08d9b0500c67
Create Date: 2026-06-28 09:39:39.660929

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3196d4def85'
down_revision: Union[str, None] = '08d9b0500c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_files',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_files_entity_id'), 'crm_files', ['entity_id'], unique=False)
    op.create_index(op.f('ix_crm_files_id'), 'crm_files', ['id'], unique=False)
    op.create_index(op.f('ix_crm_files_is_deleted'), 'crm_files', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_files_organization_id'), 'crm_files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_files_owner_id'), 'crm_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_files_public_id'), 'crm_files', ['public_id'], unique=True)
    op.create_foreign_key('fk_crm_leads_deal_id', 'crm_leads', 'crm_deals', ['deal_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_crm_leads_deal_id', 'crm_leads', type_='foreignkey')
    op.drop_index(op.f('ix_crm_files_public_id'), table_name='crm_files')
    op.drop_index(op.f('ix_crm_files_owner_id'), table_name='crm_files')
    op.drop_index(op.f('ix_crm_files_organization_id'), table_name='crm_files')
    op.drop_index(op.f('ix_crm_files_is_deleted'), table_name='crm_files')
    op.drop_index(op.f('ix_crm_files_id'), table_name='crm_files')
    op.drop_index(op.f('ix_crm_files_entity_id'), table_name='crm_files')
    op.drop_table('crm_files')
    # ### end Alembic commands ###
